version: '3.8'

services:

  # PostgreSQL for Menu Service
  menu-postgres:
    image: postgres:16
    container_name: menu_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: menu_service_db
    ports:
      - "5433:5432"
    volumes:
      - menu_pgdata:/var/lib/postgresql/data
    networks:
      - dinegrid_net

  # Redis for Caching
  redis:
    image: redis:7
    container_name: dinegrid_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dinegrid_net  

  # Menu Service Application
  menu-service:
    # build: ./menu-service
    image: neelddocker/menu-service:latest
    container_name: menu_service_app
    ports:
      - "8082:8082"
    depends_on:
      - menu-postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://menu_postgres:5432/menu_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect  # added this explicitly ✅
      SPRING_CACHE_TYPE: redis
      SPRING_DATA_REDIS_HOST: dinegrid_redis  # match container name ✅
      SPRING_DATA_REDIS_PORT: 6379
    networks:
      - dinegrid_net

volumes:
  menu_pgdata:
  redis_data:

networks:
  dinegrid_net:
    driver: bridge
